// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh5La8hklJYnq9MO17z8qEizX3pSO1Dsw',
    appId: '1:100051183998:web:979f13c872e1795aa62b2f',
    messagingSenderId: '100051183998',
    projectId: 'mynotes--ogechi--app',
    authDomain: 'mynotes--ogechi--app.firebaseapp.com',
    storageBucket: 'mynotes--ogechi--app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVSTIYp0mLKiKrgQYzVXA4-9gLRnZeeIw',
    appId: '1:100051183998:android:61c6c23ca25e70b8a62b2f',
    messagingSenderId: '100051183998',
    projectId: 'mynotes--ogechi--app',
    storageBucket: 'mynotes--ogechi--app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_9NaT80BAerVuGGRAkdAVXuvdSR_5Ks8',
    appId: '1:100051183998:ios:50acb01c3d894ae3a62b2f',
    messagingSenderId: '100051183998',
    projectId: 'mynotes--ogechi--app',
    storageBucket: 'mynotes--ogechi--app.appspot.com',
    iosClientId: '100051183998-tnsaqhju06jrdpq2g0ub5u37u4otpbmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_9NaT80BAerVuGGRAkdAVXuvdSR_5Ks8',
    appId: '1:100051183998:ios:50acb01c3d894ae3a62b2f',
    messagingSenderId: '100051183998',
    projectId: 'mynotes--ogechi--app',
    storageBucket: 'mynotes--ogechi--app.appspot.com',
    iosClientId: '100051183998-tnsaqhju06jrdpq2g0ub5u37u4otpbmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthapp',
  );
}
